version: '3'
services:
 app:
  build: .
  restart: unless-stopped
  networks:
   - web
  env_file: .env
  labels:
   traefik.frontend.rule: "Host:${DOMAIN}"
   traefik.port: "3000"
   traefik.protocol: "http"
   traefik.enable: "true"

networks:
 web:
  external:
   name: web

  
  
